var orangePrice = 20;
var chocolate = 0.5;
var applePrice = parseInt("22.5");
var grapePrice = parseFloat("20.5");
var bananaPrice = parseInt("sdhfasdf");
var pineapplePrice = "20";

console.log(typeof orangePrice);
// number;
console.log(typeof bananaPrice);
// number;
console.log(typeof pineapplePrice);
// number;
console.log(typeof grapePrice);
// number;
console.log(applePrice);
// 22;
console.log(grapePrice);
// 20.5;
console.log(bananaPrice);
// NaN_Not_a_Number;
console.log(chocolate);
// 0.5;
console.log(orangePrice + applePrice);
// 42;
console.log(orangePrice + grapePrice);
// 40.5;
console.log(orangePrice + bananaPrice);
// NaN;
console.log(orangePrice + pineapplePrice);
// 2020;

var first = 0.1;
var second = 0.2;
var third = 0.3;
var fourth = 0.4;
var total = first + second;
var total2 = third + fourth;
const num = 50 / 0;
console.log(total);
// 0.30000000000000004;
console.log(total.toFixed(5));
// 0.3;
console.log(total2);
// 0.7;
console.log(num);
// Infinity;
